// Code generated by go-swagger; DO NOT EDIT.

package g_p_g_key_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new g p g key service API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for g p g key service API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GPGKeyServiceCreate(params *GPGKeyServiceCreateParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GPGKeyServiceCreateOK, error)

	GPGKeyServiceDelete(params *GPGKeyServiceDeleteParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GPGKeyServiceDeleteOK, error)

	GPGKeyServiceGet(params *GPGKeyServiceGetParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GPGKeyServiceGetOK, error)

	GPGKeyServiceList(params *GPGKeyServiceListParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GPGKeyServiceListOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GPGKeyServiceCreate creates one or more g p g public keys in the server s configuration
*/
func (a *Client) GPGKeyServiceCreate(params *GPGKeyServiceCreateParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GPGKeyServiceCreateOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGPGKeyServiceCreateParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GPGKeyService_Create",
		Method:             "POST",
		PathPattern:        "/api/v1/gpgkeys",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GPGKeyServiceCreateReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GPGKeyServiceCreateOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GPGKeyServiceCreateDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  GPGKeyServiceDelete deletes specified g p g public key from the server s configuration
*/
func (a *Client) GPGKeyServiceDelete(params *GPGKeyServiceDeleteParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GPGKeyServiceDeleteOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGPGKeyServiceDeleteParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GPGKeyService_Delete",
		Method:             "DELETE",
		PathPattern:        "/api/v1/gpgkeys",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GPGKeyServiceDeleteReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GPGKeyServiceDeleteOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GPGKeyServiceDeleteDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  GPGKeyServiceGet gets information about specified g p g public key from the server
*/
func (a *Client) GPGKeyServiceGet(params *GPGKeyServiceGetParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GPGKeyServiceGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGPGKeyServiceGetParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GPGKeyService_Get",
		Method:             "GET",
		PathPattern:        "/api/v1/gpgkeys/{keyID}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GPGKeyServiceGetReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GPGKeyServiceGetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GPGKeyServiceGetDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  GPGKeyServiceList lists all available repository certificates
*/
func (a *Client) GPGKeyServiceList(params *GPGKeyServiceListParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GPGKeyServiceListOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGPGKeyServiceListParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GPGKeyService_List",
		Method:             "GET",
		PathPattern:        "/api/v1/gpgkeys",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GPGKeyServiceListReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GPGKeyServiceListOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GPGKeyServiceListDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
