// Code generated by go-swagger; DO NOT EDIT.

package cluster_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewClusterServiceListParams creates a new ClusterServiceListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewClusterServiceListParams() *ClusterServiceListParams {
	return &ClusterServiceListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewClusterServiceListParamsWithTimeout creates a new ClusterServiceListParams object
// with the ability to set a timeout on a request.
func NewClusterServiceListParamsWithTimeout(timeout time.Duration) *ClusterServiceListParams {
	return &ClusterServiceListParams{
		timeout: timeout,
	}
}

// NewClusterServiceListParamsWithContext creates a new ClusterServiceListParams object
// with the ability to set a context for a request.
func NewClusterServiceListParamsWithContext(ctx context.Context) *ClusterServiceListParams {
	return &ClusterServiceListParams{
		Context: ctx,
	}
}

// NewClusterServiceListParamsWithHTTPClient creates a new ClusterServiceListParams object
// with the ability to set a custom HTTPClient for a request.
func NewClusterServiceListParamsWithHTTPClient(client *http.Client) *ClusterServiceListParams {
	return &ClusterServiceListParams{
		HTTPClient: client,
	}
}

/* ClusterServiceListParams contains all the parameters to send to the API endpoint
   for the cluster service list operation.

   Typically these are written to a http.Request.
*/
type ClusterServiceListParams struct {

	/* IDType.

	   type is the type of the specified cluster identifier ( "server" - default, "name" ).
	*/
	IDType *string

	/* IDValue.

	   value holds the cluster server URL or cluster name.
	*/
	IDValue *string

	// Name.
	Name *string

	// Server.
	Server *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the cluster service list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ClusterServiceListParams) WithDefaults() *ClusterServiceListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the cluster service list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ClusterServiceListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the cluster service list params
func (o *ClusterServiceListParams) WithTimeout(timeout time.Duration) *ClusterServiceListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cluster service list params
func (o *ClusterServiceListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cluster service list params
func (o *ClusterServiceListParams) WithContext(ctx context.Context) *ClusterServiceListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cluster service list params
func (o *ClusterServiceListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the cluster service list params
func (o *ClusterServiceListParams) WithHTTPClient(client *http.Client) *ClusterServiceListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the cluster service list params
func (o *ClusterServiceListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIDType adds the iDType to the cluster service list params
func (o *ClusterServiceListParams) WithIDType(iDType *string) *ClusterServiceListParams {
	o.SetIDType(iDType)
	return o
}

// SetIDType adds the idType to the cluster service list params
func (o *ClusterServiceListParams) SetIDType(iDType *string) {
	o.IDType = iDType
}

// WithIDValue adds the iDValue to the cluster service list params
func (o *ClusterServiceListParams) WithIDValue(iDValue *string) *ClusterServiceListParams {
	o.SetIDValue(iDValue)
	return o
}

// SetIDValue adds the idValue to the cluster service list params
func (o *ClusterServiceListParams) SetIDValue(iDValue *string) {
	o.IDValue = iDValue
}

// WithName adds the name to the cluster service list params
func (o *ClusterServiceListParams) WithName(name *string) *ClusterServiceListParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the cluster service list params
func (o *ClusterServiceListParams) SetName(name *string) {
	o.Name = name
}

// WithServer adds the server to the cluster service list params
func (o *ClusterServiceListParams) WithServer(server *string) *ClusterServiceListParams {
	o.SetServer(server)
	return o
}

// SetServer adds the server to the cluster service list params
func (o *ClusterServiceListParams) SetServer(server *string) {
	o.Server = server
}

// WriteToRequest writes these params to a swagger request
func (o *ClusterServiceListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.IDType != nil {

		// query param id.type
		var qrIDType string

		if o.IDType != nil {
			qrIDType = *o.IDType
		}
		qIDType := qrIDType
		if qIDType != "" {

			if err := r.SetQueryParam("id.type", qIDType); err != nil {
				return err
			}
		}
	}

	if o.IDValue != nil {

		// query param id.value
		var qrIDValue string

		if o.IDValue != nil {
			qrIDValue = *o.IDValue
		}
		qIDValue := qrIDValue
		if qIDValue != "" {

			if err := r.SetQueryParam("id.value", qIDValue); err != nil {
				return err
			}
		}
	}

	if o.Name != nil {

		// query param name
		var qrName string

		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {

			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}
	}

	if o.Server != nil {

		// query param server
		var qrServer string

		if o.Server != nil {
			qrServer = *o.Server
		}
		qServer := qrServer
		if qServer != "" {

			if err := r.SetQueryParam("server", qServer); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
