// Code generated by go-swagger; DO NOT EDIT.

package project_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/wanddynosios/go-argocd-client/models"
)

// ProjectServiceGetGlobalProjectsReader is a Reader for the ProjectServiceGetGlobalProjects structure.
type ProjectServiceGetGlobalProjectsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProjectServiceGetGlobalProjectsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewProjectServiceGetGlobalProjectsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewProjectServiceGetGlobalProjectsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewProjectServiceGetGlobalProjectsOK creates a ProjectServiceGetGlobalProjectsOK with default headers values
func NewProjectServiceGetGlobalProjectsOK() *ProjectServiceGetGlobalProjectsOK {
	return &ProjectServiceGetGlobalProjectsOK{}
}

/* ProjectServiceGetGlobalProjectsOK describes a response with status code 200, with default header values.

A successful response.
*/
type ProjectServiceGetGlobalProjectsOK struct {
	Payload *models.ProjectGlobalProjectsResponse
}

func (o *ProjectServiceGetGlobalProjectsOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/projects/{name}/globalprojects][%d] projectServiceGetGlobalProjectsOK  %+v", 200, o.Payload)
}
func (o *ProjectServiceGetGlobalProjectsOK) GetPayload() *models.ProjectGlobalProjectsResponse {
	return o.Payload
}

func (o *ProjectServiceGetGlobalProjectsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProjectGlobalProjectsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProjectServiceGetGlobalProjectsDefault creates a ProjectServiceGetGlobalProjectsDefault with default headers values
func NewProjectServiceGetGlobalProjectsDefault(code int) *ProjectServiceGetGlobalProjectsDefault {
	return &ProjectServiceGetGlobalProjectsDefault{
		_statusCode: code,
	}
}

/* ProjectServiceGetGlobalProjectsDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ProjectServiceGetGlobalProjectsDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the project service get global projects default response
func (o *ProjectServiceGetGlobalProjectsDefault) Code() int {
	return o._statusCode
}

func (o *ProjectServiceGetGlobalProjectsDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/projects/{name}/globalprojects][%d] ProjectService_GetGlobalProjects default  %+v", o._statusCode, o.Payload)
}
func (o *ProjectServiceGetGlobalProjectsDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *ProjectServiceGetGlobalProjectsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
