// Code generated by go-swagger; DO NOT EDIT.

package project_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewProjectServiceListEventsParams creates a new ProjectServiceListEventsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewProjectServiceListEventsParams() *ProjectServiceListEventsParams {
	return &ProjectServiceListEventsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewProjectServiceListEventsParamsWithTimeout creates a new ProjectServiceListEventsParams object
// with the ability to set a timeout on a request.
func NewProjectServiceListEventsParamsWithTimeout(timeout time.Duration) *ProjectServiceListEventsParams {
	return &ProjectServiceListEventsParams{
		timeout: timeout,
	}
}

// NewProjectServiceListEventsParamsWithContext creates a new ProjectServiceListEventsParams object
// with the ability to set a context for a request.
func NewProjectServiceListEventsParamsWithContext(ctx context.Context) *ProjectServiceListEventsParams {
	return &ProjectServiceListEventsParams{
		Context: ctx,
	}
}

// NewProjectServiceListEventsParamsWithHTTPClient creates a new ProjectServiceListEventsParams object
// with the ability to set a custom HTTPClient for a request.
func NewProjectServiceListEventsParamsWithHTTPClient(client *http.Client) *ProjectServiceListEventsParams {
	return &ProjectServiceListEventsParams{
		HTTPClient: client,
	}
}

/* ProjectServiceListEventsParams contains all the parameters to send to the API endpoint
   for the project service list events operation.

   Typically these are written to a http.Request.
*/
type ProjectServiceListEventsParams struct {

	// Name.
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the project service list events params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ProjectServiceListEventsParams) WithDefaults() *ProjectServiceListEventsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the project service list events params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ProjectServiceListEventsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the project service list events params
func (o *ProjectServiceListEventsParams) WithTimeout(timeout time.Duration) *ProjectServiceListEventsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the project service list events params
func (o *ProjectServiceListEventsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the project service list events params
func (o *ProjectServiceListEventsParams) WithContext(ctx context.Context) *ProjectServiceListEventsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the project service list events params
func (o *ProjectServiceListEventsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the project service list events params
func (o *ProjectServiceListEventsParams) WithHTTPClient(client *http.Client) *ProjectServiceListEventsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the project service list events params
func (o *ProjectServiceListEventsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the project service list events params
func (o *ProjectServiceListEventsParams) WithName(name string) *ProjectServiceListEventsParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the project service list events params
func (o *ProjectServiceListEventsParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *ProjectServiceListEventsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
