// Code generated by go-swagger; DO NOT EDIT.

package project_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewProjectServiceGetGlobalProjectsParams creates a new ProjectServiceGetGlobalProjectsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewProjectServiceGetGlobalProjectsParams() *ProjectServiceGetGlobalProjectsParams {
	return &ProjectServiceGetGlobalProjectsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewProjectServiceGetGlobalProjectsParamsWithTimeout creates a new ProjectServiceGetGlobalProjectsParams object
// with the ability to set a timeout on a request.
func NewProjectServiceGetGlobalProjectsParamsWithTimeout(timeout time.Duration) *ProjectServiceGetGlobalProjectsParams {
	return &ProjectServiceGetGlobalProjectsParams{
		timeout: timeout,
	}
}

// NewProjectServiceGetGlobalProjectsParamsWithContext creates a new ProjectServiceGetGlobalProjectsParams object
// with the ability to set a context for a request.
func NewProjectServiceGetGlobalProjectsParamsWithContext(ctx context.Context) *ProjectServiceGetGlobalProjectsParams {
	return &ProjectServiceGetGlobalProjectsParams{
		Context: ctx,
	}
}

// NewProjectServiceGetGlobalProjectsParamsWithHTTPClient creates a new ProjectServiceGetGlobalProjectsParams object
// with the ability to set a custom HTTPClient for a request.
func NewProjectServiceGetGlobalProjectsParamsWithHTTPClient(client *http.Client) *ProjectServiceGetGlobalProjectsParams {
	return &ProjectServiceGetGlobalProjectsParams{
		HTTPClient: client,
	}
}

/* ProjectServiceGetGlobalProjectsParams contains all the parameters to send to the API endpoint
   for the project service get global projects operation.

   Typically these are written to a http.Request.
*/
type ProjectServiceGetGlobalProjectsParams struct {

	// Name.
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the project service get global projects params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ProjectServiceGetGlobalProjectsParams) WithDefaults() *ProjectServiceGetGlobalProjectsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the project service get global projects params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ProjectServiceGetGlobalProjectsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the project service get global projects params
func (o *ProjectServiceGetGlobalProjectsParams) WithTimeout(timeout time.Duration) *ProjectServiceGetGlobalProjectsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the project service get global projects params
func (o *ProjectServiceGetGlobalProjectsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the project service get global projects params
func (o *ProjectServiceGetGlobalProjectsParams) WithContext(ctx context.Context) *ProjectServiceGetGlobalProjectsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the project service get global projects params
func (o *ProjectServiceGetGlobalProjectsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the project service get global projects params
func (o *ProjectServiceGetGlobalProjectsParams) WithHTTPClient(client *http.Client) *ProjectServiceGetGlobalProjectsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the project service get global projects params
func (o *ProjectServiceGetGlobalProjectsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the project service get global projects params
func (o *ProjectServiceGetGlobalProjectsParams) WithName(name string) *ProjectServiceGetGlobalProjectsParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the project service get global projects params
func (o *ProjectServiceGetGlobalProjectsParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *ProjectServiceGetGlobalProjectsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
