// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/wanddynosios/go-argocd-client/models"
)

// ApplicationServiceCreateReader is a Reader for the ApplicationServiceCreate structure.
type ApplicationServiceCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ApplicationServiceCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewApplicationServiceCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewApplicationServiceCreateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewApplicationServiceCreateOK creates a ApplicationServiceCreateOK with default headers values
func NewApplicationServiceCreateOK() *ApplicationServiceCreateOK {
	return &ApplicationServiceCreateOK{}
}

/* ApplicationServiceCreateOK describes a response with status code 200, with default header values.

A successful response.
*/
type ApplicationServiceCreateOK struct {
	Payload *models.V1alpha1Application
}

func (o *ApplicationServiceCreateOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/applications][%d] applicationServiceCreateOK  %+v", 200, o.Payload)
}
func (o *ApplicationServiceCreateOK) GetPayload() *models.V1alpha1Application {
	return o.Payload
}

func (o *ApplicationServiceCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1Application)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewApplicationServiceCreateDefault creates a ApplicationServiceCreateDefault with default headers values
func NewApplicationServiceCreateDefault(code int) *ApplicationServiceCreateDefault {
	return &ApplicationServiceCreateDefault{
		_statusCode: code,
	}
}

/* ApplicationServiceCreateDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ApplicationServiceCreateDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the application service create default response
func (o *ApplicationServiceCreateDefault) Code() int {
	return o._statusCode
}

func (o *ApplicationServiceCreateDefault) Error() string {
	return fmt.Sprintf("[POST /api/v1/applications][%d] ApplicationService_Create default  %+v", o._statusCode, o.Payload)
}
func (o *ApplicationServiceCreateDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *ApplicationServiceCreateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
