// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewApplicationServiceRunResourceActionParams creates a new ApplicationServiceRunResourceActionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewApplicationServiceRunResourceActionParams() *ApplicationServiceRunResourceActionParams {
	return &ApplicationServiceRunResourceActionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewApplicationServiceRunResourceActionParamsWithTimeout creates a new ApplicationServiceRunResourceActionParams object
// with the ability to set a timeout on a request.
func NewApplicationServiceRunResourceActionParamsWithTimeout(timeout time.Duration) *ApplicationServiceRunResourceActionParams {
	return &ApplicationServiceRunResourceActionParams{
		timeout: timeout,
	}
}

// NewApplicationServiceRunResourceActionParamsWithContext creates a new ApplicationServiceRunResourceActionParams object
// with the ability to set a context for a request.
func NewApplicationServiceRunResourceActionParamsWithContext(ctx context.Context) *ApplicationServiceRunResourceActionParams {
	return &ApplicationServiceRunResourceActionParams{
		Context: ctx,
	}
}

// NewApplicationServiceRunResourceActionParamsWithHTTPClient creates a new ApplicationServiceRunResourceActionParams object
// with the ability to set a custom HTTPClient for a request.
func NewApplicationServiceRunResourceActionParamsWithHTTPClient(client *http.Client) *ApplicationServiceRunResourceActionParams {
	return &ApplicationServiceRunResourceActionParams{
		HTTPClient: client,
	}
}

/* ApplicationServiceRunResourceActionParams contains all the parameters to send to the API endpoint
   for the application service run resource action operation.

   Typically these are written to a http.Request.
*/
type ApplicationServiceRunResourceActionParams struct {

	// Body.
	Body string

	// Group.
	Group *string

	// Kind.
	Kind *string

	// Name.
	Name string

	// Namespace.
	Namespace *string

	// ResourceName.
	ResourceName *string

	// Version.
	Version *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the application service run resource action params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ApplicationServiceRunResourceActionParams) WithDefaults() *ApplicationServiceRunResourceActionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the application service run resource action params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ApplicationServiceRunResourceActionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the application service run resource action params
func (o *ApplicationServiceRunResourceActionParams) WithTimeout(timeout time.Duration) *ApplicationServiceRunResourceActionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the application service run resource action params
func (o *ApplicationServiceRunResourceActionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the application service run resource action params
func (o *ApplicationServiceRunResourceActionParams) WithContext(ctx context.Context) *ApplicationServiceRunResourceActionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the application service run resource action params
func (o *ApplicationServiceRunResourceActionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the application service run resource action params
func (o *ApplicationServiceRunResourceActionParams) WithHTTPClient(client *http.Client) *ApplicationServiceRunResourceActionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the application service run resource action params
func (o *ApplicationServiceRunResourceActionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the application service run resource action params
func (o *ApplicationServiceRunResourceActionParams) WithBody(body string) *ApplicationServiceRunResourceActionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the application service run resource action params
func (o *ApplicationServiceRunResourceActionParams) SetBody(body string) {
	o.Body = body
}

// WithGroup adds the group to the application service run resource action params
func (o *ApplicationServiceRunResourceActionParams) WithGroup(group *string) *ApplicationServiceRunResourceActionParams {
	o.SetGroup(group)
	return o
}

// SetGroup adds the group to the application service run resource action params
func (o *ApplicationServiceRunResourceActionParams) SetGroup(group *string) {
	o.Group = group
}

// WithKind adds the kind to the application service run resource action params
func (o *ApplicationServiceRunResourceActionParams) WithKind(kind *string) *ApplicationServiceRunResourceActionParams {
	o.SetKind(kind)
	return o
}

// SetKind adds the kind to the application service run resource action params
func (o *ApplicationServiceRunResourceActionParams) SetKind(kind *string) {
	o.Kind = kind
}

// WithName adds the name to the application service run resource action params
func (o *ApplicationServiceRunResourceActionParams) WithName(name string) *ApplicationServiceRunResourceActionParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the application service run resource action params
func (o *ApplicationServiceRunResourceActionParams) SetName(name string) {
	o.Name = name
}

// WithNamespace adds the namespace to the application service run resource action params
func (o *ApplicationServiceRunResourceActionParams) WithNamespace(namespace *string) *ApplicationServiceRunResourceActionParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the application service run resource action params
func (o *ApplicationServiceRunResourceActionParams) SetNamespace(namespace *string) {
	o.Namespace = namespace
}

// WithResourceName adds the resourceName to the application service run resource action params
func (o *ApplicationServiceRunResourceActionParams) WithResourceName(resourceName *string) *ApplicationServiceRunResourceActionParams {
	o.SetResourceName(resourceName)
	return o
}

// SetResourceName adds the resourceName to the application service run resource action params
func (o *ApplicationServiceRunResourceActionParams) SetResourceName(resourceName *string) {
	o.ResourceName = resourceName
}

// WithVersion adds the version to the application service run resource action params
func (o *ApplicationServiceRunResourceActionParams) WithVersion(version *string) *ApplicationServiceRunResourceActionParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the application service run resource action params
func (o *ApplicationServiceRunResourceActionParams) SetVersion(version *string) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *ApplicationServiceRunResourceActionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if o.Group != nil {

		// query param group
		var qrGroup string

		if o.Group != nil {
			qrGroup = *o.Group
		}
		qGroup := qrGroup
		if qGroup != "" {

			if err := r.SetQueryParam("group", qGroup); err != nil {
				return err
			}
		}
	}

	if o.Kind != nil {

		// query param kind
		var qrKind string

		if o.Kind != nil {
			qrKind = *o.Kind
		}
		qKind := qrKind
		if qKind != "" {

			if err := r.SetQueryParam("kind", qKind); err != nil {
				return err
			}
		}
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if o.Namespace != nil {

		// query param namespace
		var qrNamespace string

		if o.Namespace != nil {
			qrNamespace = *o.Namespace
		}
		qNamespace := qrNamespace
		if qNamespace != "" {

			if err := r.SetQueryParam("namespace", qNamespace); err != nil {
				return err
			}
		}
	}

	if o.ResourceName != nil {

		// query param resourceName
		var qrResourceName string

		if o.ResourceName != nil {
			qrResourceName = *o.ResourceName
		}
		qResourceName := qrResourceName
		if qResourceName != "" {

			if err := r.SetQueryParam("resourceName", qResourceName); err != nil {
				return err
			}
		}
	}

	if o.Version != nil {

		// query param version
		var qrVersion string

		if o.Version != nil {
			qrVersion = *o.Version
		}
		qVersion := qrVersion
		if qVersion != "" {

			if err := r.SetQueryParam("version", qVersion); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
