// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/wanddynosios/go-argocd-client/models"
)

// ApplicationServiceRevisionMetadataReader is a Reader for the ApplicationServiceRevisionMetadata structure.
type ApplicationServiceRevisionMetadataReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ApplicationServiceRevisionMetadataReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewApplicationServiceRevisionMetadataOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewApplicationServiceRevisionMetadataDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewApplicationServiceRevisionMetadataOK creates a ApplicationServiceRevisionMetadataOK with default headers values
func NewApplicationServiceRevisionMetadataOK() *ApplicationServiceRevisionMetadataOK {
	return &ApplicationServiceRevisionMetadataOK{}
}

/* ApplicationServiceRevisionMetadataOK describes a response with status code 200, with default header values.

A successful response.
*/
type ApplicationServiceRevisionMetadataOK struct {
	Payload *models.V1alpha1RevisionMetadata
}

func (o *ApplicationServiceRevisionMetadataOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/applications/{name}/revisions/{revision}/metadata][%d] applicationServiceRevisionMetadataOK  %+v", 200, o.Payload)
}
func (o *ApplicationServiceRevisionMetadataOK) GetPayload() *models.V1alpha1RevisionMetadata {
	return o.Payload
}

func (o *ApplicationServiceRevisionMetadataOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1RevisionMetadata)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewApplicationServiceRevisionMetadataDefault creates a ApplicationServiceRevisionMetadataDefault with default headers values
func NewApplicationServiceRevisionMetadataDefault(code int) *ApplicationServiceRevisionMetadataDefault {
	return &ApplicationServiceRevisionMetadataDefault{
		_statusCode: code,
	}
}

/* ApplicationServiceRevisionMetadataDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ApplicationServiceRevisionMetadataDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the application service revision metadata default response
func (o *ApplicationServiceRevisionMetadataDefault) Code() int {
	return o._statusCode
}

func (o *ApplicationServiceRevisionMetadataDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/applications/{name}/revisions/{revision}/metadata][%d] ApplicationService_RevisionMetadata default  %+v", o._statusCode, o.Payload)
}
func (o *ApplicationServiceRevisionMetadataDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *ApplicationServiceRevisionMetadataDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
