// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/wanddynosios/go-argocd-client/models"
)

// NewApplicationServiceUpdateParams creates a new ApplicationServiceUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewApplicationServiceUpdateParams() *ApplicationServiceUpdateParams {
	return &ApplicationServiceUpdateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewApplicationServiceUpdateParamsWithTimeout creates a new ApplicationServiceUpdateParams object
// with the ability to set a timeout on a request.
func NewApplicationServiceUpdateParamsWithTimeout(timeout time.Duration) *ApplicationServiceUpdateParams {
	return &ApplicationServiceUpdateParams{
		timeout: timeout,
	}
}

// NewApplicationServiceUpdateParamsWithContext creates a new ApplicationServiceUpdateParams object
// with the ability to set a context for a request.
func NewApplicationServiceUpdateParamsWithContext(ctx context.Context) *ApplicationServiceUpdateParams {
	return &ApplicationServiceUpdateParams{
		Context: ctx,
	}
}

// NewApplicationServiceUpdateParamsWithHTTPClient creates a new ApplicationServiceUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewApplicationServiceUpdateParamsWithHTTPClient(client *http.Client) *ApplicationServiceUpdateParams {
	return &ApplicationServiceUpdateParams{
		HTTPClient: client,
	}
}

/* ApplicationServiceUpdateParams contains all the parameters to send to the API endpoint
   for the application service update operation.

   Typically these are written to a http.Request.
*/
type ApplicationServiceUpdateParams struct {

	/* ApplicationMetadataName.

	     Name must be unique within a namespace. Is required when creating resources, although
	some resources may allow a client to request the generation of an appropriate name
	automatically. Name is primarily intended for creation idempotence and configuration
	definition.
	Cannot be updated.
	More info: http://kubernetes.io/docs/user-guide/identifiers#names
	+optional
	*/
	ApplicationMetadataName string

	// Body.
	Body *models.V1alpha1Application

	// Validate.
	Validate *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the application service update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ApplicationServiceUpdateParams) WithDefaults() *ApplicationServiceUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the application service update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ApplicationServiceUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the application service update params
func (o *ApplicationServiceUpdateParams) WithTimeout(timeout time.Duration) *ApplicationServiceUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the application service update params
func (o *ApplicationServiceUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the application service update params
func (o *ApplicationServiceUpdateParams) WithContext(ctx context.Context) *ApplicationServiceUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the application service update params
func (o *ApplicationServiceUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the application service update params
func (o *ApplicationServiceUpdateParams) WithHTTPClient(client *http.Client) *ApplicationServiceUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the application service update params
func (o *ApplicationServiceUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApplicationMetadataName adds the applicationMetadataName to the application service update params
func (o *ApplicationServiceUpdateParams) WithApplicationMetadataName(applicationMetadataName string) *ApplicationServiceUpdateParams {
	o.SetApplicationMetadataName(applicationMetadataName)
	return o
}

// SetApplicationMetadataName adds the applicationMetadataName to the application service update params
func (o *ApplicationServiceUpdateParams) SetApplicationMetadataName(applicationMetadataName string) {
	o.ApplicationMetadataName = applicationMetadataName
}

// WithBody adds the body to the application service update params
func (o *ApplicationServiceUpdateParams) WithBody(body *models.V1alpha1Application) *ApplicationServiceUpdateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the application service update params
func (o *ApplicationServiceUpdateParams) SetBody(body *models.V1alpha1Application) {
	o.Body = body
}

// WithValidate adds the validate to the application service update params
func (o *ApplicationServiceUpdateParams) WithValidate(validate *bool) *ApplicationServiceUpdateParams {
	o.SetValidate(validate)
	return o
}

// SetValidate adds the validate to the application service update params
func (o *ApplicationServiceUpdateParams) SetValidate(validate *bool) {
	o.Validate = validate
}

// WriteToRequest writes these params to a swagger request
func (o *ApplicationServiceUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param application.metadata.name
	if err := r.SetPathParam("application.metadata.name", o.ApplicationMetadataName); err != nil {
		return err
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if o.Validate != nil {

		// query param validate
		var qrValidate bool

		if o.Validate != nil {
			qrValidate = *o.Validate
		}
		qValidate := swag.FormatBool(qrValidate)
		if qValidate != "" {

			if err := r.SetQueryParam("validate", qValidate); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
