// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/wanddynosios/go-argocd-client/models"
)

// ApplicationServiceListResourceActionsReader is a Reader for the ApplicationServiceListResourceActions structure.
type ApplicationServiceListResourceActionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ApplicationServiceListResourceActionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewApplicationServiceListResourceActionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewApplicationServiceListResourceActionsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewApplicationServiceListResourceActionsOK creates a ApplicationServiceListResourceActionsOK with default headers values
func NewApplicationServiceListResourceActionsOK() *ApplicationServiceListResourceActionsOK {
	return &ApplicationServiceListResourceActionsOK{}
}

/* ApplicationServiceListResourceActionsOK describes a response with status code 200, with default header values.

A successful response.
*/
type ApplicationServiceListResourceActionsOK struct {
	Payload *models.ApplicationResourceActionsListResponse
}

func (o *ApplicationServiceListResourceActionsOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/applications/{name}/resource/actions][%d] applicationServiceListResourceActionsOK  %+v", 200, o.Payload)
}
func (o *ApplicationServiceListResourceActionsOK) GetPayload() *models.ApplicationResourceActionsListResponse {
	return o.Payload
}

func (o *ApplicationServiceListResourceActionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApplicationResourceActionsListResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewApplicationServiceListResourceActionsDefault creates a ApplicationServiceListResourceActionsDefault with default headers values
func NewApplicationServiceListResourceActionsDefault(code int) *ApplicationServiceListResourceActionsDefault {
	return &ApplicationServiceListResourceActionsDefault{
		_statusCode: code,
	}
}

/* ApplicationServiceListResourceActionsDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ApplicationServiceListResourceActionsDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the application service list resource actions default response
func (o *ApplicationServiceListResourceActionsDefault) Code() int {
	return o._statusCode
}

func (o *ApplicationServiceListResourceActionsDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/applications/{name}/resource/actions][%d] ApplicationService_ListResourceActions default  %+v", o._statusCode, o.Payload)
}
func (o *ApplicationServiceListResourceActionsDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *ApplicationServiceListResourceActionsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
