// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/wanddynosios/go-argocd-client/models"
)

// NewApplicationServiceRollbackParams creates a new ApplicationServiceRollbackParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewApplicationServiceRollbackParams() *ApplicationServiceRollbackParams {
	return &ApplicationServiceRollbackParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewApplicationServiceRollbackParamsWithTimeout creates a new ApplicationServiceRollbackParams object
// with the ability to set a timeout on a request.
func NewApplicationServiceRollbackParamsWithTimeout(timeout time.Duration) *ApplicationServiceRollbackParams {
	return &ApplicationServiceRollbackParams{
		timeout: timeout,
	}
}

// NewApplicationServiceRollbackParamsWithContext creates a new ApplicationServiceRollbackParams object
// with the ability to set a context for a request.
func NewApplicationServiceRollbackParamsWithContext(ctx context.Context) *ApplicationServiceRollbackParams {
	return &ApplicationServiceRollbackParams{
		Context: ctx,
	}
}

// NewApplicationServiceRollbackParamsWithHTTPClient creates a new ApplicationServiceRollbackParams object
// with the ability to set a custom HTTPClient for a request.
func NewApplicationServiceRollbackParamsWithHTTPClient(client *http.Client) *ApplicationServiceRollbackParams {
	return &ApplicationServiceRollbackParams{
		HTTPClient: client,
	}
}

/* ApplicationServiceRollbackParams contains all the parameters to send to the API endpoint
   for the application service rollback operation.

   Typically these are written to a http.Request.
*/
type ApplicationServiceRollbackParams struct {

	// Body.
	Body *models.ApplicationApplicationRollbackRequest

	// Name.
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the application service rollback params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ApplicationServiceRollbackParams) WithDefaults() *ApplicationServiceRollbackParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the application service rollback params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ApplicationServiceRollbackParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the application service rollback params
func (o *ApplicationServiceRollbackParams) WithTimeout(timeout time.Duration) *ApplicationServiceRollbackParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the application service rollback params
func (o *ApplicationServiceRollbackParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the application service rollback params
func (o *ApplicationServiceRollbackParams) WithContext(ctx context.Context) *ApplicationServiceRollbackParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the application service rollback params
func (o *ApplicationServiceRollbackParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the application service rollback params
func (o *ApplicationServiceRollbackParams) WithHTTPClient(client *http.Client) *ApplicationServiceRollbackParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the application service rollback params
func (o *ApplicationServiceRollbackParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the application service rollback params
func (o *ApplicationServiceRollbackParams) WithBody(body *models.ApplicationApplicationRollbackRequest) *ApplicationServiceRollbackParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the application service rollback params
func (o *ApplicationServiceRollbackParams) SetBody(body *models.ApplicationApplicationRollbackRequest) {
	o.Body = body
}

// WithName adds the name to the application service rollback params
func (o *ApplicationServiceRollbackParams) WithName(name string) *ApplicationServiceRollbackParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the application service rollback params
func (o *ApplicationServiceRollbackParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *ApplicationServiceRollbackParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
