// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/wanddynosios/go-argocd-client/models"
)

// ApplicationServiceWatchResourceTreeReader is a Reader for the ApplicationServiceWatchResourceTree structure.
type ApplicationServiceWatchResourceTreeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ApplicationServiceWatchResourceTreeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewApplicationServiceWatchResourceTreeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewApplicationServiceWatchResourceTreeDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewApplicationServiceWatchResourceTreeOK creates a ApplicationServiceWatchResourceTreeOK with default headers values
func NewApplicationServiceWatchResourceTreeOK() *ApplicationServiceWatchResourceTreeOK {
	return &ApplicationServiceWatchResourceTreeOK{}
}

/* ApplicationServiceWatchResourceTreeOK describes a response with status code 200, with default header values.

A successful response.(streaming responses)
*/
type ApplicationServiceWatchResourceTreeOK struct {
	Payload *ApplicationServiceWatchResourceTreeOKBody
}

func (o *ApplicationServiceWatchResourceTreeOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/stream/applications/{applicationName}/resource-tree][%d] applicationServiceWatchResourceTreeOK  %+v", 200, o.Payload)
}
func (o *ApplicationServiceWatchResourceTreeOK) GetPayload() *ApplicationServiceWatchResourceTreeOKBody {
	return o.Payload
}

func (o *ApplicationServiceWatchResourceTreeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ApplicationServiceWatchResourceTreeOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewApplicationServiceWatchResourceTreeDefault creates a ApplicationServiceWatchResourceTreeDefault with default headers values
func NewApplicationServiceWatchResourceTreeDefault(code int) *ApplicationServiceWatchResourceTreeDefault {
	return &ApplicationServiceWatchResourceTreeDefault{
		_statusCode: code,
	}
}

/* ApplicationServiceWatchResourceTreeDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ApplicationServiceWatchResourceTreeDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the application service watch resource tree default response
func (o *ApplicationServiceWatchResourceTreeDefault) Code() int {
	return o._statusCode
}

func (o *ApplicationServiceWatchResourceTreeDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/stream/applications/{applicationName}/resource-tree][%d] ApplicationService_WatchResourceTree default  %+v", o._statusCode, o.Payload)
}
func (o *ApplicationServiceWatchResourceTreeDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *ApplicationServiceWatchResourceTreeDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*ApplicationServiceWatchResourceTreeOKBody Stream result of v1alpha1ApplicationTree
swagger:model ApplicationServiceWatchResourceTreeOKBody
*/
type ApplicationServiceWatchResourceTreeOKBody struct {

	// error
	Error *models.RuntimeStreamError `json:"error,omitempty"`

	// result
	Result *models.V1alpha1ApplicationTree `json:"result,omitempty"`
}

// Validate validates this application service watch resource tree o k body
func (o *ApplicationServiceWatchResourceTreeOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ApplicationServiceWatchResourceTreeOKBody) validateError(formats strfmt.Registry) error {
	if swag.IsZero(o.Error) { // not required
		return nil
	}

	if o.Error != nil {
		if err := o.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("applicationServiceWatchResourceTreeOK" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("applicationServiceWatchResourceTreeOK" + "." + "error")
			}
			return err
		}
	}

	return nil
}

func (o *ApplicationServiceWatchResourceTreeOKBody) validateResult(formats strfmt.Registry) error {
	if swag.IsZero(o.Result) { // not required
		return nil
	}

	if o.Result != nil {
		if err := o.Result.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("applicationServiceWatchResourceTreeOK" + "." + "result")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("applicationServiceWatchResourceTreeOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this application service watch resource tree o k body based on the context it is used
func (o *ApplicationServiceWatchResourceTreeOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateError(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateResult(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ApplicationServiceWatchResourceTreeOKBody) contextValidateError(ctx context.Context, formats strfmt.Registry) error {

	if o.Error != nil {
		if err := o.Error.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("applicationServiceWatchResourceTreeOK" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("applicationServiceWatchResourceTreeOK" + "." + "error")
			}
			return err
		}
	}

	return nil
}

func (o *ApplicationServiceWatchResourceTreeOKBody) contextValidateResult(ctx context.Context, formats strfmt.Registry) error {

	if o.Result != nil {
		if err := o.Result.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("applicationServiceWatchResourceTreeOK" + "." + "result")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("applicationServiceWatchResourceTreeOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *ApplicationServiceWatchResourceTreeOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ApplicationServiceWatchResourceTreeOKBody) UnmarshalBinary(b []byte) error {
	var res ApplicationServiceWatchResourceTreeOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
