// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/wanddynosios/go-argocd-client/models"
)

// NewApplicationServiceUpdateSpecParams creates a new ApplicationServiceUpdateSpecParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewApplicationServiceUpdateSpecParams() *ApplicationServiceUpdateSpecParams {
	return &ApplicationServiceUpdateSpecParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewApplicationServiceUpdateSpecParamsWithTimeout creates a new ApplicationServiceUpdateSpecParams object
// with the ability to set a timeout on a request.
func NewApplicationServiceUpdateSpecParamsWithTimeout(timeout time.Duration) *ApplicationServiceUpdateSpecParams {
	return &ApplicationServiceUpdateSpecParams{
		timeout: timeout,
	}
}

// NewApplicationServiceUpdateSpecParamsWithContext creates a new ApplicationServiceUpdateSpecParams object
// with the ability to set a context for a request.
func NewApplicationServiceUpdateSpecParamsWithContext(ctx context.Context) *ApplicationServiceUpdateSpecParams {
	return &ApplicationServiceUpdateSpecParams{
		Context: ctx,
	}
}

// NewApplicationServiceUpdateSpecParamsWithHTTPClient creates a new ApplicationServiceUpdateSpecParams object
// with the ability to set a custom HTTPClient for a request.
func NewApplicationServiceUpdateSpecParamsWithHTTPClient(client *http.Client) *ApplicationServiceUpdateSpecParams {
	return &ApplicationServiceUpdateSpecParams{
		HTTPClient: client,
	}
}

/* ApplicationServiceUpdateSpecParams contains all the parameters to send to the API endpoint
   for the application service update spec operation.

   Typically these are written to a http.Request.
*/
type ApplicationServiceUpdateSpecParams struct {

	// Body.
	Body *models.V1alpha1ApplicationSpec

	// Name.
	Name string

	// Validate.
	Validate *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the application service update spec params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ApplicationServiceUpdateSpecParams) WithDefaults() *ApplicationServiceUpdateSpecParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the application service update spec params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ApplicationServiceUpdateSpecParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the application service update spec params
func (o *ApplicationServiceUpdateSpecParams) WithTimeout(timeout time.Duration) *ApplicationServiceUpdateSpecParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the application service update spec params
func (o *ApplicationServiceUpdateSpecParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the application service update spec params
func (o *ApplicationServiceUpdateSpecParams) WithContext(ctx context.Context) *ApplicationServiceUpdateSpecParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the application service update spec params
func (o *ApplicationServiceUpdateSpecParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the application service update spec params
func (o *ApplicationServiceUpdateSpecParams) WithHTTPClient(client *http.Client) *ApplicationServiceUpdateSpecParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the application service update spec params
func (o *ApplicationServiceUpdateSpecParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the application service update spec params
func (o *ApplicationServiceUpdateSpecParams) WithBody(body *models.V1alpha1ApplicationSpec) *ApplicationServiceUpdateSpecParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the application service update spec params
func (o *ApplicationServiceUpdateSpecParams) SetBody(body *models.V1alpha1ApplicationSpec) {
	o.Body = body
}

// WithName adds the name to the application service update spec params
func (o *ApplicationServiceUpdateSpecParams) WithName(name string) *ApplicationServiceUpdateSpecParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the application service update spec params
func (o *ApplicationServiceUpdateSpecParams) SetName(name string) {
	o.Name = name
}

// WithValidate adds the validate to the application service update spec params
func (o *ApplicationServiceUpdateSpecParams) WithValidate(validate *bool) *ApplicationServiceUpdateSpecParams {
	o.SetValidate(validate)
	return o
}

// SetValidate adds the validate to the application service update spec params
func (o *ApplicationServiceUpdateSpecParams) SetValidate(validate *bool) {
	o.Validate = validate
}

// WriteToRequest writes these params to a swagger request
func (o *ApplicationServiceUpdateSpecParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if o.Validate != nil {

		// query param validate
		var qrValidate bool

		if o.Validate != nil {
			qrValidate = *o.Validate
		}
		qValidate := swag.FormatBool(qrValidate)
		if qValidate != "" {

			if err := r.SetQueryParam("validate", qValidate); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
