// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/wanddynosios/go-argocd-client/models"
)

// ApplicationServiceDeleteResourceReader is a Reader for the ApplicationServiceDeleteResource structure.
type ApplicationServiceDeleteResourceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ApplicationServiceDeleteResourceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewApplicationServiceDeleteResourceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewApplicationServiceDeleteResourceDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewApplicationServiceDeleteResourceOK creates a ApplicationServiceDeleteResourceOK with default headers values
func NewApplicationServiceDeleteResourceOK() *ApplicationServiceDeleteResourceOK {
	return &ApplicationServiceDeleteResourceOK{}
}

/* ApplicationServiceDeleteResourceOK describes a response with status code 200, with default header values.

A successful response.
*/
type ApplicationServiceDeleteResourceOK struct {
	Payload models.ApplicationApplicationResponse
}

func (o *ApplicationServiceDeleteResourceOK) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/applications/{name}/resource][%d] applicationServiceDeleteResourceOK  %+v", 200, o.Payload)
}
func (o *ApplicationServiceDeleteResourceOK) GetPayload() models.ApplicationApplicationResponse {
	return o.Payload
}

func (o *ApplicationServiceDeleteResourceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewApplicationServiceDeleteResourceDefault creates a ApplicationServiceDeleteResourceDefault with default headers values
func NewApplicationServiceDeleteResourceDefault(code int) *ApplicationServiceDeleteResourceDefault {
	return &ApplicationServiceDeleteResourceDefault{
		_statusCode: code,
	}
}

/* ApplicationServiceDeleteResourceDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ApplicationServiceDeleteResourceDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the application service delete resource default response
func (o *ApplicationServiceDeleteResourceDefault) Code() int {
	return o._statusCode
}

func (o *ApplicationServiceDeleteResourceDefault) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/applications/{name}/resource][%d] ApplicationService_DeleteResource default  %+v", o._statusCode, o.Payload)
}
func (o *ApplicationServiceDeleteResourceDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *ApplicationServiceDeleteResourceDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
