// Code generated by go-swagger; DO NOT EDIT.

package session_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/wanddynosios/go-argocd-client/models"
)

// SessionServiceGetUserInfoReader is a Reader for the SessionServiceGetUserInfo structure.
type SessionServiceGetUserInfoReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SessionServiceGetUserInfoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSessionServiceGetUserInfoOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSessionServiceGetUserInfoDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSessionServiceGetUserInfoOK creates a SessionServiceGetUserInfoOK with default headers values
func NewSessionServiceGetUserInfoOK() *SessionServiceGetUserInfoOK {
	return &SessionServiceGetUserInfoOK{}
}

/* SessionServiceGetUserInfoOK describes a response with status code 200, with default header values.

A successful response.
*/
type SessionServiceGetUserInfoOK struct {
	Payload *models.SessionGetUserInfoResponse
}

func (o *SessionServiceGetUserInfoOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/session/userinfo][%d] sessionServiceGetUserInfoOK  %+v", 200, o.Payload)
}
func (o *SessionServiceGetUserInfoOK) GetPayload() *models.SessionGetUserInfoResponse {
	return o.Payload
}

func (o *SessionServiceGetUserInfoOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SessionGetUserInfoResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSessionServiceGetUserInfoDefault creates a SessionServiceGetUserInfoDefault with default headers values
func NewSessionServiceGetUserInfoDefault(code int) *SessionServiceGetUserInfoDefault {
	return &SessionServiceGetUserInfoDefault{
		_statusCode: code,
	}
}

/* SessionServiceGetUserInfoDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type SessionServiceGetUserInfoDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the session service get user info default response
func (o *SessionServiceGetUserInfoDefault) Code() int {
	return o._statusCode
}

func (o *SessionServiceGetUserInfoDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/session/userinfo][%d] SessionService_GetUserInfo default  %+v", o._statusCode, o.Payload)
}
func (o *SessionServiceGetUserInfoDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *SessionServiceGetUserInfoDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
