// Code generated by go-swagger; DO NOT EDIT.

package account_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/wanddynosios/go-argocd-client/models"
)

// AccountServiceCanIReader is a Reader for the AccountServiceCanI structure.
type AccountServiceCanIReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AccountServiceCanIReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAccountServiceCanIOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewAccountServiceCanIDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewAccountServiceCanIOK creates a AccountServiceCanIOK with default headers values
func NewAccountServiceCanIOK() *AccountServiceCanIOK {
	return &AccountServiceCanIOK{}
}

/* AccountServiceCanIOK describes a response with status code 200, with default header values.

A successful response.
*/
type AccountServiceCanIOK struct {
	Payload *models.AccountCanIResponse
}

func (o *AccountServiceCanIOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/account/can-i/{resource}/{action}/{subresource}][%d] accountServiceCanIOK  %+v", 200, o.Payload)
}
func (o *AccountServiceCanIOK) GetPayload() *models.AccountCanIResponse {
	return o.Payload
}

func (o *AccountServiceCanIOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AccountCanIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAccountServiceCanIDefault creates a AccountServiceCanIDefault with default headers values
func NewAccountServiceCanIDefault(code int) *AccountServiceCanIDefault {
	return &AccountServiceCanIDefault{
		_statusCode: code,
	}
}

/* AccountServiceCanIDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type AccountServiceCanIDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the account service can i default response
func (o *AccountServiceCanIDefault) Code() int {
	return o._statusCode
}

func (o *AccountServiceCanIDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/account/can-i/{resource}/{action}/{subresource}][%d] AccountService_CanI default  %+v", o._statusCode, o.Payload)
}
func (o *AccountServiceCanIDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *AccountServiceCanIDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
