// Code generated by go-swagger; DO NOT EDIT.

package account_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/wanddynosios/go-argocd-client/models"
)

// AccountServiceUpdatePasswordReader is a Reader for the AccountServiceUpdatePassword structure.
type AccountServiceUpdatePasswordReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AccountServiceUpdatePasswordReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAccountServiceUpdatePasswordOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewAccountServiceUpdatePasswordDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewAccountServiceUpdatePasswordOK creates a AccountServiceUpdatePasswordOK with default headers values
func NewAccountServiceUpdatePasswordOK() *AccountServiceUpdatePasswordOK {
	return &AccountServiceUpdatePasswordOK{}
}

/* AccountServiceUpdatePasswordOK describes a response with status code 200, with default header values.

A successful response.
*/
type AccountServiceUpdatePasswordOK struct {
	Payload models.AccountUpdatePasswordResponse
}

func (o *AccountServiceUpdatePasswordOK) Error() string {
	return fmt.Sprintf("[PUT /api/v1/account/password][%d] accountServiceUpdatePasswordOK  %+v", 200, o.Payload)
}
func (o *AccountServiceUpdatePasswordOK) GetPayload() models.AccountUpdatePasswordResponse {
	return o.Payload
}

func (o *AccountServiceUpdatePasswordOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAccountServiceUpdatePasswordDefault creates a AccountServiceUpdatePasswordDefault with default headers values
func NewAccountServiceUpdatePasswordDefault(code int) *AccountServiceUpdatePasswordDefault {
	return &AccountServiceUpdatePasswordDefault{
		_statusCode: code,
	}
}

/* AccountServiceUpdatePasswordDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type AccountServiceUpdatePasswordDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the account service update password default response
func (o *AccountServiceUpdatePasswordDefault) Code() int {
	return o._statusCode
}

func (o *AccountServiceUpdatePasswordDefault) Error() string {
	return fmt.Sprintf("[PUT /api/v1/account/password][%d] AccountService_UpdatePassword default  %+v", o._statusCode, o.Payload)
}
func (o *AccountServiceUpdatePasswordDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *AccountServiceUpdatePasswordDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
