// Code generated by go-swagger; DO NOT EDIT.

package account_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/wanddynosios/go-argocd-client/models"
)

// AccountServiceDeleteTokenReader is a Reader for the AccountServiceDeleteToken structure.
type AccountServiceDeleteTokenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AccountServiceDeleteTokenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAccountServiceDeleteTokenOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewAccountServiceDeleteTokenDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewAccountServiceDeleteTokenOK creates a AccountServiceDeleteTokenOK with default headers values
func NewAccountServiceDeleteTokenOK() *AccountServiceDeleteTokenOK {
	return &AccountServiceDeleteTokenOK{}
}

/* AccountServiceDeleteTokenOK describes a response with status code 200, with default header values.

A successful response.
*/
type AccountServiceDeleteTokenOK struct {
	Payload models.AccountEmptyResponse
}

func (o *AccountServiceDeleteTokenOK) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/account/{name}/token/{id}][%d] accountServiceDeleteTokenOK  %+v", 200, o.Payload)
}
func (o *AccountServiceDeleteTokenOK) GetPayload() models.AccountEmptyResponse {
	return o.Payload
}

func (o *AccountServiceDeleteTokenOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAccountServiceDeleteTokenDefault creates a AccountServiceDeleteTokenDefault with default headers values
func NewAccountServiceDeleteTokenDefault(code int) *AccountServiceDeleteTokenDefault {
	return &AccountServiceDeleteTokenDefault{
		_statusCode: code,
	}
}

/* AccountServiceDeleteTokenDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type AccountServiceDeleteTokenDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the account service delete token default response
func (o *AccountServiceDeleteTokenDefault) Code() int {
	return o._statusCode
}

func (o *AccountServiceDeleteTokenDefault) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/account/{name}/token/{id}][%d] AccountService_DeleteToken default  %+v", o._statusCode, o.Payload)
}
func (o *AccountServiceDeleteTokenDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *AccountServiceDeleteTokenDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
