// Code generated by go-swagger; DO NOT EDIT.

package repository_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/wanddynosios/go-argocd-client/models"
)

// RepositoryServiceListRepositoriesReader is a Reader for the RepositoryServiceListRepositories structure.
type RepositoryServiceListRepositoriesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RepositoryServiceListRepositoriesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRepositoryServiceListRepositoriesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRepositoryServiceListRepositoriesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRepositoryServiceListRepositoriesOK creates a RepositoryServiceListRepositoriesOK with default headers values
func NewRepositoryServiceListRepositoriesOK() *RepositoryServiceListRepositoriesOK {
	return &RepositoryServiceListRepositoriesOK{}
}

/* RepositoryServiceListRepositoriesOK describes a response with status code 200, with default header values.

A successful response.
*/
type RepositoryServiceListRepositoriesOK struct {
	Payload *models.V1alpha1RepositoryList
}

func (o *RepositoryServiceListRepositoriesOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/repositories][%d] repositoryServiceListRepositoriesOK  %+v", 200, o.Payload)
}
func (o *RepositoryServiceListRepositoriesOK) GetPayload() *models.V1alpha1RepositoryList {
	return o.Payload
}

func (o *RepositoryServiceListRepositoriesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1RepositoryList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRepositoryServiceListRepositoriesDefault creates a RepositoryServiceListRepositoriesDefault with default headers values
func NewRepositoryServiceListRepositoriesDefault(code int) *RepositoryServiceListRepositoriesDefault {
	return &RepositoryServiceListRepositoriesDefault{
		_statusCode: code,
	}
}

/* RepositoryServiceListRepositoriesDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type RepositoryServiceListRepositoriesDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the repository service list repositories default response
func (o *RepositoryServiceListRepositoriesDefault) Code() int {
	return o._statusCode
}

func (o *RepositoryServiceListRepositoriesDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/repositories][%d] RepositoryService_ListRepositories default  %+v", o._statusCode, o.Payload)
}
func (o *RepositoryServiceListRepositoriesDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *RepositoryServiceListRepositoriesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
