// Code generated by go-swagger; DO NOT EDIT.

package repository_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/wanddynosios/go-argocd-client/models"
)

// RepositoryServiceValidateAccessReader is a Reader for the RepositoryServiceValidateAccess structure.
type RepositoryServiceValidateAccessReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RepositoryServiceValidateAccessReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRepositoryServiceValidateAccessOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRepositoryServiceValidateAccessDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRepositoryServiceValidateAccessOK creates a RepositoryServiceValidateAccessOK with default headers values
func NewRepositoryServiceValidateAccessOK() *RepositoryServiceValidateAccessOK {
	return &RepositoryServiceValidateAccessOK{}
}

/* RepositoryServiceValidateAccessOK describes a response with status code 200, with default header values.

A successful response.
*/
type RepositoryServiceValidateAccessOK struct {
	Payload models.RepositoryRepoResponse
}

func (o *RepositoryServiceValidateAccessOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/repositories/{repo}/validate][%d] repositoryServiceValidateAccessOK  %+v", 200, o.Payload)
}
func (o *RepositoryServiceValidateAccessOK) GetPayload() models.RepositoryRepoResponse {
	return o.Payload
}

func (o *RepositoryServiceValidateAccessOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRepositoryServiceValidateAccessDefault creates a RepositoryServiceValidateAccessDefault with default headers values
func NewRepositoryServiceValidateAccessDefault(code int) *RepositoryServiceValidateAccessDefault {
	return &RepositoryServiceValidateAccessDefault{
		_statusCode: code,
	}
}

/* RepositoryServiceValidateAccessDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type RepositoryServiceValidateAccessDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the repository service validate access default response
func (o *RepositoryServiceValidateAccessDefault) Code() int {
	return o._statusCode
}

func (o *RepositoryServiceValidateAccessDefault) Error() string {
	return fmt.Sprintf("[POST /api/v1/repositories/{repo}/validate][%d] RepositoryService_ValidateAccess default  %+v", o._statusCode, o.Payload)
}
func (o *RepositoryServiceValidateAccessDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *RepositoryServiceValidateAccessDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
