// Code generated by go-swagger; DO NOT EDIT.

package repository_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewRepositoryServiceGetParams creates a new RepositoryServiceGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRepositoryServiceGetParams() *RepositoryServiceGetParams {
	return &RepositoryServiceGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRepositoryServiceGetParamsWithTimeout creates a new RepositoryServiceGetParams object
// with the ability to set a timeout on a request.
func NewRepositoryServiceGetParamsWithTimeout(timeout time.Duration) *RepositoryServiceGetParams {
	return &RepositoryServiceGetParams{
		timeout: timeout,
	}
}

// NewRepositoryServiceGetParamsWithContext creates a new RepositoryServiceGetParams object
// with the ability to set a context for a request.
func NewRepositoryServiceGetParamsWithContext(ctx context.Context) *RepositoryServiceGetParams {
	return &RepositoryServiceGetParams{
		Context: ctx,
	}
}

// NewRepositoryServiceGetParamsWithHTTPClient creates a new RepositoryServiceGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewRepositoryServiceGetParamsWithHTTPClient(client *http.Client) *RepositoryServiceGetParams {
	return &RepositoryServiceGetParams{
		HTTPClient: client,
	}
}

/* RepositoryServiceGetParams contains all the parameters to send to the API endpoint
   for the repository service get operation.

   Typically these are written to a http.Request.
*/
type RepositoryServiceGetParams struct {

	/* ForceRefresh.

	   Whether to force a cache refresh on repo's connection state.
	*/
	ForceRefresh *bool

	/* Repo.

	   Repo URL for query
	*/
	Repo string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the repository service get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RepositoryServiceGetParams) WithDefaults() *RepositoryServiceGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the repository service get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RepositoryServiceGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the repository service get params
func (o *RepositoryServiceGetParams) WithTimeout(timeout time.Duration) *RepositoryServiceGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the repository service get params
func (o *RepositoryServiceGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the repository service get params
func (o *RepositoryServiceGetParams) WithContext(ctx context.Context) *RepositoryServiceGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the repository service get params
func (o *RepositoryServiceGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the repository service get params
func (o *RepositoryServiceGetParams) WithHTTPClient(client *http.Client) *RepositoryServiceGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the repository service get params
func (o *RepositoryServiceGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithForceRefresh adds the forceRefresh to the repository service get params
func (o *RepositoryServiceGetParams) WithForceRefresh(forceRefresh *bool) *RepositoryServiceGetParams {
	o.SetForceRefresh(forceRefresh)
	return o
}

// SetForceRefresh adds the forceRefresh to the repository service get params
func (o *RepositoryServiceGetParams) SetForceRefresh(forceRefresh *bool) {
	o.ForceRefresh = forceRefresh
}

// WithRepo adds the repo to the repository service get params
func (o *RepositoryServiceGetParams) WithRepo(repo string) *RepositoryServiceGetParams {
	o.SetRepo(repo)
	return o
}

// SetRepo adds the repo to the repository service get params
func (o *RepositoryServiceGetParams) SetRepo(repo string) {
	o.Repo = repo
}

// WriteToRequest writes these params to a swagger request
func (o *RepositoryServiceGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ForceRefresh != nil {

		// query param forceRefresh
		var qrForceRefresh bool

		if o.ForceRefresh != nil {
			qrForceRefresh = *o.ForceRefresh
		}
		qForceRefresh := swag.FormatBool(qrForceRefresh)
		if qForceRefresh != "" {

			if err := r.SetQueryParam("forceRefresh", qForceRefresh); err != nil {
				return err
			}
		}
	}

	// path param repo
	if err := r.SetPathParam("repo", o.Repo); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
