// Code generated by go-swagger; DO NOT EDIT.

package repository_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/wanddynosios/go-argocd-client/models"
)

// RepositoryServiceGetHelmChartsReader is a Reader for the RepositoryServiceGetHelmCharts structure.
type RepositoryServiceGetHelmChartsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RepositoryServiceGetHelmChartsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRepositoryServiceGetHelmChartsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRepositoryServiceGetHelmChartsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRepositoryServiceGetHelmChartsOK creates a RepositoryServiceGetHelmChartsOK with default headers values
func NewRepositoryServiceGetHelmChartsOK() *RepositoryServiceGetHelmChartsOK {
	return &RepositoryServiceGetHelmChartsOK{}
}

/* RepositoryServiceGetHelmChartsOK describes a response with status code 200, with default header values.

A successful response.
*/
type RepositoryServiceGetHelmChartsOK struct {
	Payload *models.RepositoryHelmChartsResponse
}

func (o *RepositoryServiceGetHelmChartsOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/repositories/{repo}/helmcharts][%d] repositoryServiceGetHelmChartsOK  %+v", 200, o.Payload)
}
func (o *RepositoryServiceGetHelmChartsOK) GetPayload() *models.RepositoryHelmChartsResponse {
	return o.Payload
}

func (o *RepositoryServiceGetHelmChartsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RepositoryHelmChartsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRepositoryServiceGetHelmChartsDefault creates a RepositoryServiceGetHelmChartsDefault with default headers values
func NewRepositoryServiceGetHelmChartsDefault(code int) *RepositoryServiceGetHelmChartsDefault {
	return &RepositoryServiceGetHelmChartsDefault{
		_statusCode: code,
	}
}

/* RepositoryServiceGetHelmChartsDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type RepositoryServiceGetHelmChartsDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the repository service get helm charts default response
func (o *RepositoryServiceGetHelmChartsDefault) Code() int {
	return o._statusCode
}

func (o *RepositoryServiceGetHelmChartsDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/repositories/{repo}/helmcharts][%d] RepositoryService_GetHelmCharts default  %+v", o._statusCode, o.Payload)
}
func (o *RepositoryServiceGetHelmChartsDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *RepositoryServiceGetHelmChartsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
