// Code generated by go-swagger; DO NOT EDIT.

package repo_creds_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRepoCredsServiceDeleteRepositoryCredentialsParams creates a new RepoCredsServiceDeleteRepositoryCredentialsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRepoCredsServiceDeleteRepositoryCredentialsParams() *RepoCredsServiceDeleteRepositoryCredentialsParams {
	return &RepoCredsServiceDeleteRepositoryCredentialsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRepoCredsServiceDeleteRepositoryCredentialsParamsWithTimeout creates a new RepoCredsServiceDeleteRepositoryCredentialsParams object
// with the ability to set a timeout on a request.
func NewRepoCredsServiceDeleteRepositoryCredentialsParamsWithTimeout(timeout time.Duration) *RepoCredsServiceDeleteRepositoryCredentialsParams {
	return &RepoCredsServiceDeleteRepositoryCredentialsParams{
		timeout: timeout,
	}
}

// NewRepoCredsServiceDeleteRepositoryCredentialsParamsWithContext creates a new RepoCredsServiceDeleteRepositoryCredentialsParams object
// with the ability to set a context for a request.
func NewRepoCredsServiceDeleteRepositoryCredentialsParamsWithContext(ctx context.Context) *RepoCredsServiceDeleteRepositoryCredentialsParams {
	return &RepoCredsServiceDeleteRepositoryCredentialsParams{
		Context: ctx,
	}
}

// NewRepoCredsServiceDeleteRepositoryCredentialsParamsWithHTTPClient creates a new RepoCredsServiceDeleteRepositoryCredentialsParams object
// with the ability to set a custom HTTPClient for a request.
func NewRepoCredsServiceDeleteRepositoryCredentialsParamsWithHTTPClient(client *http.Client) *RepoCredsServiceDeleteRepositoryCredentialsParams {
	return &RepoCredsServiceDeleteRepositoryCredentialsParams{
		HTTPClient: client,
	}
}

/* RepoCredsServiceDeleteRepositoryCredentialsParams contains all the parameters to send to the API endpoint
   for the repo creds service delete repository credentials operation.

   Typically these are written to a http.Request.
*/
type RepoCredsServiceDeleteRepositoryCredentialsParams struct {

	// URL.
	URL string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the repo creds service delete repository credentials params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RepoCredsServiceDeleteRepositoryCredentialsParams) WithDefaults() *RepoCredsServiceDeleteRepositoryCredentialsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the repo creds service delete repository credentials params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RepoCredsServiceDeleteRepositoryCredentialsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the repo creds service delete repository credentials params
func (o *RepoCredsServiceDeleteRepositoryCredentialsParams) WithTimeout(timeout time.Duration) *RepoCredsServiceDeleteRepositoryCredentialsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the repo creds service delete repository credentials params
func (o *RepoCredsServiceDeleteRepositoryCredentialsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the repo creds service delete repository credentials params
func (o *RepoCredsServiceDeleteRepositoryCredentialsParams) WithContext(ctx context.Context) *RepoCredsServiceDeleteRepositoryCredentialsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the repo creds service delete repository credentials params
func (o *RepoCredsServiceDeleteRepositoryCredentialsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the repo creds service delete repository credentials params
func (o *RepoCredsServiceDeleteRepositoryCredentialsParams) WithHTTPClient(client *http.Client) *RepoCredsServiceDeleteRepositoryCredentialsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the repo creds service delete repository credentials params
func (o *RepoCredsServiceDeleteRepositoryCredentialsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithURL adds the url to the repo creds service delete repository credentials params
func (o *RepoCredsServiceDeleteRepositoryCredentialsParams) WithURL(url string) *RepoCredsServiceDeleteRepositoryCredentialsParams {
	o.SetURL(url)
	return o
}

// SetURL adds the url to the repo creds service delete repository credentials params
func (o *RepoCredsServiceDeleteRepositoryCredentialsParams) SetURL(url string) {
	o.URL = url
}

// WriteToRequest writes these params to a swagger request
func (o *RepoCredsServiceDeleteRepositoryCredentialsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param url
	if err := r.SetPathParam("url", o.URL); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
