// Code generated by go-swagger; DO NOT EDIT.

package repo_creds_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/wanddynosios/go-argocd-client/models"
)

// RepoCredsServiceCreateRepositoryCredentialsReader is a Reader for the RepoCredsServiceCreateRepositoryCredentials structure.
type RepoCredsServiceCreateRepositoryCredentialsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RepoCredsServiceCreateRepositoryCredentialsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRepoCredsServiceCreateRepositoryCredentialsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRepoCredsServiceCreateRepositoryCredentialsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRepoCredsServiceCreateRepositoryCredentialsOK creates a RepoCredsServiceCreateRepositoryCredentialsOK with default headers values
func NewRepoCredsServiceCreateRepositoryCredentialsOK() *RepoCredsServiceCreateRepositoryCredentialsOK {
	return &RepoCredsServiceCreateRepositoryCredentialsOK{}
}

/* RepoCredsServiceCreateRepositoryCredentialsOK describes a response with status code 200, with default header values.

A successful response.
*/
type RepoCredsServiceCreateRepositoryCredentialsOK struct {
	Payload *models.V1alpha1RepoCreds
}

func (o *RepoCredsServiceCreateRepositoryCredentialsOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/repocreds][%d] repoCredsServiceCreateRepositoryCredentialsOK  %+v", 200, o.Payload)
}
func (o *RepoCredsServiceCreateRepositoryCredentialsOK) GetPayload() *models.V1alpha1RepoCreds {
	return o.Payload
}

func (o *RepoCredsServiceCreateRepositoryCredentialsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1RepoCreds)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRepoCredsServiceCreateRepositoryCredentialsDefault creates a RepoCredsServiceCreateRepositoryCredentialsDefault with default headers values
func NewRepoCredsServiceCreateRepositoryCredentialsDefault(code int) *RepoCredsServiceCreateRepositoryCredentialsDefault {
	return &RepoCredsServiceCreateRepositoryCredentialsDefault{
		_statusCode: code,
	}
}

/* RepoCredsServiceCreateRepositoryCredentialsDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type RepoCredsServiceCreateRepositoryCredentialsDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the repo creds service create repository credentials default response
func (o *RepoCredsServiceCreateRepositoryCredentialsDefault) Code() int {
	return o._statusCode
}

func (o *RepoCredsServiceCreateRepositoryCredentialsDefault) Error() string {
	return fmt.Sprintf("[POST /api/v1/repocreds][%d] RepoCredsService_CreateRepositoryCredentials default  %+v", o._statusCode, o.Payload)
}
func (o *RepoCredsServiceCreateRepositoryCredentialsDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *RepoCredsServiceCreateRepositoryCredentialsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
