// Code generated by go-swagger; DO NOT EDIT.

package repo_creds_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/wanddynosios/go-argocd-client/models"
)

// RepoCredsServiceUpdateRepositoryCredentialsReader is a Reader for the RepoCredsServiceUpdateRepositoryCredentials structure.
type RepoCredsServiceUpdateRepositoryCredentialsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RepoCredsServiceUpdateRepositoryCredentialsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRepoCredsServiceUpdateRepositoryCredentialsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRepoCredsServiceUpdateRepositoryCredentialsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRepoCredsServiceUpdateRepositoryCredentialsOK creates a RepoCredsServiceUpdateRepositoryCredentialsOK with default headers values
func NewRepoCredsServiceUpdateRepositoryCredentialsOK() *RepoCredsServiceUpdateRepositoryCredentialsOK {
	return &RepoCredsServiceUpdateRepositoryCredentialsOK{}
}

/* RepoCredsServiceUpdateRepositoryCredentialsOK describes a response with status code 200, with default header values.

A successful response.
*/
type RepoCredsServiceUpdateRepositoryCredentialsOK struct {
	Payload *models.V1alpha1RepoCreds
}

func (o *RepoCredsServiceUpdateRepositoryCredentialsOK) Error() string {
	return fmt.Sprintf("[PUT /api/v1/repocreds/{creds.url}][%d] repoCredsServiceUpdateRepositoryCredentialsOK  %+v", 200, o.Payload)
}
func (o *RepoCredsServiceUpdateRepositoryCredentialsOK) GetPayload() *models.V1alpha1RepoCreds {
	return o.Payload
}

func (o *RepoCredsServiceUpdateRepositoryCredentialsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1RepoCreds)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRepoCredsServiceUpdateRepositoryCredentialsDefault creates a RepoCredsServiceUpdateRepositoryCredentialsDefault with default headers values
func NewRepoCredsServiceUpdateRepositoryCredentialsDefault(code int) *RepoCredsServiceUpdateRepositoryCredentialsDefault {
	return &RepoCredsServiceUpdateRepositoryCredentialsDefault{
		_statusCode: code,
	}
}

/* RepoCredsServiceUpdateRepositoryCredentialsDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type RepoCredsServiceUpdateRepositoryCredentialsDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the repo creds service update repository credentials default response
func (o *RepoCredsServiceUpdateRepositoryCredentialsDefault) Code() int {
	return o._statusCode
}

func (o *RepoCredsServiceUpdateRepositoryCredentialsDefault) Error() string {
	return fmt.Sprintf("[PUT /api/v1/repocreds/{creds.url}][%d] RepoCredsService_UpdateRepositoryCredentials default  %+v", o._statusCode, o.Payload)
}
func (o *RepoCredsServiceUpdateRepositoryCredentialsDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *RepoCredsServiceUpdateRepositoryCredentialsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
