// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ClusterOIDCConfig cluster o ID c config
//
// swagger:model clusterOIDCConfig
type ClusterOIDCConfig struct {

	// cli client ID
	CliClientID string `json:"cliClientID,omitempty"`

	// client ID
	ClientID string `json:"clientID,omitempty"`

	// id token claims
	IDTokenClaims map[string]OidcClaim `json:"idTokenClaims,omitempty"`

	// issuer
	Issuer string `json:"issuer,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// scopes
	Scopes []string `json:"scopes"`
}

// Validate validates this cluster o ID c config
func (m *ClusterOIDCConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateIDTokenClaims(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ClusterOIDCConfig) validateIDTokenClaims(formats strfmt.Registry) error {
	if swag.IsZero(m.IDTokenClaims) { // not required
		return nil
	}

	for k := range m.IDTokenClaims {

		if err := validate.Required("idTokenClaims"+"."+k, "body", m.IDTokenClaims[k]); err != nil {
			return err
		}
		if val, ok := m.IDTokenClaims[k]; ok {
			if err := val.Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("idTokenClaims" + "." + k)
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("idTokenClaims" + "." + k)
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this cluster o ID c config based on the context it is used
func (m *ClusterOIDCConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateIDTokenClaims(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ClusterOIDCConfig) contextValidateIDTokenClaims(ctx context.Context, formats strfmt.Registry) error {

	for k := range m.IDTokenClaims {

		if val, ok := m.IDTokenClaims[k]; ok {
			if err := val.ContextValidate(ctx, formats); err != nil {
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ClusterOIDCConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClusterOIDCConfig) UnmarshalBinary(b []byte) error {
	var res ClusterOIDCConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
