// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1ResourceNode ResourceNode contains information about live resource and its children
// TODO: describe members of this type
//
// swagger:model v1alpha1ResourceNode
type V1alpha1ResourceNode struct {

	// created at
	CreatedAt *V1Time `json:"createdAt,omitempty"`

	// health
	Health *V1alpha1HealthStatus `json:"health,omitempty"`

	// images
	Images []string `json:"images"`

	// info
	Info []*V1alpha1InfoItem `json:"info"`

	// networking info
	NetworkingInfo *V1alpha1ResourceNetworkingInfo `json:"networkingInfo,omitempty"`

	// parent refs
	ParentRefs []*V1alpha1ResourceRef `json:"parentRefs"`

	// resource ref
	ResourceRef *V1alpha1ResourceRef `json:"resourceRef,omitempty"`

	// resource version
	ResourceVersion string `json:"resourceVersion,omitempty"`
}

// Validate validates this v1alpha1 resource node
func (m *V1alpha1ResourceNode) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHealth(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInfo(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNetworkingInfo(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateParentRefs(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResourceRef(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1ResourceNode) validateCreatedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.CreatedAt) { // not required
		return nil
	}

	if m.CreatedAt != nil {
		if err := m.CreatedAt.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("createdAt")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("createdAt")
			}
			return err
		}
	}

	return nil
}

func (m *V1alpha1ResourceNode) validateHealth(formats strfmt.Registry) error {
	if swag.IsZero(m.Health) { // not required
		return nil
	}

	if m.Health != nil {
		if err := m.Health.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("health")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("health")
			}
			return err
		}
	}

	return nil
}

func (m *V1alpha1ResourceNode) validateInfo(formats strfmt.Registry) error {
	if swag.IsZero(m.Info) { // not required
		return nil
	}

	for i := 0; i < len(m.Info); i++ {
		if swag.IsZero(m.Info[i]) { // not required
			continue
		}

		if m.Info[i] != nil {
			if err := m.Info[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("info" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("info" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *V1alpha1ResourceNode) validateNetworkingInfo(formats strfmt.Registry) error {
	if swag.IsZero(m.NetworkingInfo) { // not required
		return nil
	}

	if m.NetworkingInfo != nil {
		if err := m.NetworkingInfo.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("networkingInfo")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("networkingInfo")
			}
			return err
		}
	}

	return nil
}

func (m *V1alpha1ResourceNode) validateParentRefs(formats strfmt.Registry) error {
	if swag.IsZero(m.ParentRefs) { // not required
		return nil
	}

	for i := 0; i < len(m.ParentRefs); i++ {
		if swag.IsZero(m.ParentRefs[i]) { // not required
			continue
		}

		if m.ParentRefs[i] != nil {
			if err := m.ParentRefs[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("parentRefs" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("parentRefs" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *V1alpha1ResourceNode) validateResourceRef(formats strfmt.Registry) error {
	if swag.IsZero(m.ResourceRef) { // not required
		return nil
	}

	if m.ResourceRef != nil {
		if err := m.ResourceRef.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("resourceRef")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("resourceRef")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this v1alpha1 resource node based on the context it is used
func (m *V1alpha1ResourceNode) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCreatedAt(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateHealth(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateInfo(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateNetworkingInfo(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateParentRefs(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateResourceRef(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1ResourceNode) contextValidateCreatedAt(ctx context.Context, formats strfmt.Registry) error {

	if m.CreatedAt != nil {
		if err := m.CreatedAt.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("createdAt")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("createdAt")
			}
			return err
		}
	}

	return nil
}

func (m *V1alpha1ResourceNode) contextValidateHealth(ctx context.Context, formats strfmt.Registry) error {

	if m.Health != nil {
		if err := m.Health.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("health")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("health")
			}
			return err
		}
	}

	return nil
}

func (m *V1alpha1ResourceNode) contextValidateInfo(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Info); i++ {

		if m.Info[i] != nil {
			if err := m.Info[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("info" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("info" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *V1alpha1ResourceNode) contextValidateNetworkingInfo(ctx context.Context, formats strfmt.Registry) error {

	if m.NetworkingInfo != nil {
		if err := m.NetworkingInfo.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("networkingInfo")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("networkingInfo")
			}
			return err
		}
	}

	return nil
}

func (m *V1alpha1ResourceNode) contextValidateParentRefs(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ParentRefs); i++ {

		if m.ParentRefs[i] != nil {
			if err := m.ParentRefs[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("parentRefs" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("parentRefs" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *V1alpha1ResourceNode) contextValidateResourceRef(ctx context.Context, formats strfmt.Registry) error {

	if m.ResourceRef != nil {
		if err := m.ResourceRef.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("resourceRef")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("resourceRef")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1ResourceNode) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1ResourceNode) UnmarshalBinary(b []byte) error {
	var res V1alpha1ResourceNode
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
