// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1SignatureKey SignatureKey is the specification of a key required to verify commit signatures with
//
// swagger:model v1alpha1SignatureKey
type V1alpha1SignatureKey struct {

	// The ID of the key in hexadecimal notation
	KeyID string `json:"keyID,omitempty"`
}

// Validate validates this v1alpha1 signature key
func (m *V1alpha1SignatureKey) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1alpha1 signature key based on context it is used
func (m *V1alpha1SignatureKey) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1SignatureKey) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1SignatureKey) UnmarshalBinary(b []byte) error {
	var res V1alpha1SignatureKey
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
