// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1OrphanedResourcesMonitorSettings OrphanedResourcesMonitorSettings holds settings of orphaned resources monitoring
//
// swagger:model v1alpha1OrphanedResourcesMonitorSettings
type V1alpha1OrphanedResourcesMonitorSettings struct {

	// Ignore contains a list of resources that are to be excluded from orphaned resources monitoring
	Ignore []*V1alpha1OrphanedResourceKey `json:"ignore"`

	// Warn indicates if warning condition should be created for apps which have orphaned resources
	Warn bool `json:"warn,omitempty"`
}

// Validate validates this v1alpha1 orphaned resources monitor settings
func (m *V1alpha1OrphanedResourcesMonitorSettings) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateIgnore(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1OrphanedResourcesMonitorSettings) validateIgnore(formats strfmt.Registry) error {
	if swag.IsZero(m.Ignore) { // not required
		return nil
	}

	for i := 0; i < len(m.Ignore); i++ {
		if swag.IsZero(m.Ignore[i]) { // not required
			continue
		}

		if m.Ignore[i] != nil {
			if err := m.Ignore[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("ignore" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("ignore" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this v1alpha1 orphaned resources monitor settings based on the context it is used
func (m *V1alpha1OrphanedResourcesMonitorSettings) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateIgnore(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1OrphanedResourcesMonitorSettings) contextValidateIgnore(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Ignore); i++ {

		if m.Ignore[i] != nil {
			if err := m.Ignore[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("ignore" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("ignore" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1OrphanedResourcesMonitorSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1OrphanedResourcesMonitorSettings) UnmarshalBinary(b []byte) error {
	var res V1alpha1OrphanedResourcesMonitorSettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
