// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1Backoff Backoff is the backoff strategy to use on subsequent retries for failing syncs
//
// swagger:model v1alpha1Backoff
type V1alpha1Backoff struct {

	// Duration is the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
	Duration string `json:"duration,omitempty"`

	// Factor is a factor to multiply the base duration after each failed retry
	Factor string `json:"factor,omitempty"`

	// MaxDuration is the maximum amount of time allowed for the backoff strategy
	MaxDuration string `json:"maxDuration,omitempty"`
}

// Validate validates this v1alpha1 backoff
func (m *V1alpha1Backoff) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1alpha1 backoff based on context it is used
func (m *V1alpha1Backoff) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1Backoff) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1Backoff) UnmarshalBinary(b []byte) error {
	var res V1alpha1Backoff
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
